# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptti', '0002_auto_20161008_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name': 'Administrador'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name': 'Estudiante'},
        ),
        migrations.AlterModelOptions(
            name='sicologo',
            options={'verbose_name': 'Sicologo'},
        ),
    ]
